### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by lizz-34** [hall/little-buddy#2]
Great to see another open-source firmware for earbuds/headphones (I think PineBuds Pro is just the beginning)! You are welcome to the [Discord/Matrix/Telegram rooms of PineBuds Pro](https://wiki.pine64.org/wiki/Main_Page#Chat_Platforms) (if you are not already there). And thanks for your work!

**Comment by hall** [comment]
Hey @lizz-34, thanks for the comments! Just joined the Matrix room. I'll probably (eventually) offer some of this work into the OpenPineBuds project (if they don't beat me to it) as I don't intend on developing this project for long (and wasn't aware of the other when I started).

**Comment by lizz-34** [comment]
> Hey @lizz-34, thanks for the comments! Just joined the Matrix room. 

Nice to see you there. Especially at the beginning, we should work together, although of course everybuddy don't have to. The most important thing is that we have a living community, when that is the case, new devices will come and I believe that these firmwares will eventually become quite universal (of course, embedded devices with their firmware are different from PCs, but they can work on many devices with minor changes. They can be standard, etc.).

> I'll probably (eventually) offer some of this work into the OpenPineBuds project (if they don't beat me to it) as I don't intend on developing this project for long (and wasn't aware of the other when I started).

I understand that projects like this takes time and effort, and not everyone will be very long-lived. Nevertheless, every project is valuable and important.
