### ISSUE TITLE
missing dependency jq?

### ISSUE THREAD

**Issue by yjftsjthsd-g** [hall/little-buddy#3]
Attempting to run the flash command in the readme, I got this:
```
$ nix run 'github:hall/little-buddy#flash'
/nix/store/f5341i865vzzaha9k88zlgv538xi58y9-flash/bin/flash: line 24: jq: command not found
```
(and also some permission errors that are my own problem)

Adding `jq` to my system environment removed that error, so I think your flake is missing an explicit dependency on `jq` somewhere - unfortunately, my nix skills are weak enough that I don't know where or this would be a PR:)

**Comment by hall** [comment]
Hey @yjftsjthsd-g; thanks for submitting an issue! I've pushed [a commit to not rely on implicit `jq` or `curl` packages](https://github.com/hall/little-buddy/commit/1e9b4f137bbd87eb6b1a13a4c24aaf985c9cd1f0).

Give that a go and let me know if you have any other trouble.
